insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (223, 'Wheelchairs', 'Kshlerin Inc', 4, 143);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (224, 'Stretchers', 'Becker and Sons', 2, 139);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (225, 'IV stands', 'Goyette and Sons', 4, 102);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (226, 'X-ray machines', 'Gutkowski-Lindgren', 5, 128);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (227, 'Ultrasound machines', 'O''Conner Inc', 5, 116);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (228, 'CT scanners', 'Upton LLC', 1, 179);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (229, 'MRI machines', 'Johnson Group', 1, 142);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (230, 'ECG monitors', 'Cronin-Kiehn', 3, 181);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (231, 'Defibrillators', 'Connelly, Runte and Denesik', 3, 164);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (232, 'Oxygen concentrators', 'Funk-Batz', 5, 142);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (233, 'Anesthesia machines', 'Runolfsdottir-Tromp', 1, 199);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (234, 'Ventilators', 'Kris-Parisian', 4, 120);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (235, 'Surgical lights', 'Bruen LLC', 4, 106);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (236, 'Surgical tables', 'Thiel-Goyette', 1, 138);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (237, 'Surgical instruments', 'Jacobs, Gutmann and Klein', 4, 107);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (238, 'Blood pressure monitors', 'Streich-Torp', 1, 178);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (239, 'Syringe pumps', 'Lockman-Konopelski', 3, 104);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (240, 'Infusion pumps', 'Reichel and Sons', 2, 106);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (241, 'Suction machines', 'Sporer Inc', 4, 192);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (242, 'Pulse oximeters', 'Hayes Inc', 3, 156);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (243, 'Autoclaves', 'D Amore-Predovic', 2, 171);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (244, 'Sterilizers', 'Dicki, Bauch and Kassulke', 4, 189);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (245, 'Electrocardiogram (ECG) machines', 'DuBuque and Sons', 4, 168);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (246, 'Blood gas analyzers', 'Purdy Group', 4, 194);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (247, 'Incubators', 'Lesch, Lemke and Shanahan', 4, 135);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (248, 'Radiology film processors', 'Morar, Metz and Sporer', 5, 175);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (249, 'Mobile medical carts', 'Berge, Trantow and Armstrong', 2, 158);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (250, 'Exam tables', 'Wunsch, Christiansen and Goldner', 4, 110);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (251, 'Crash carts', 'Morissette-Cruickshank', 2, 173);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (252, 'Nebulizers', 'Bode-Crona', 3, 151);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (253, 'EKG machines', 'Hammes, McGlynn and Walsh', 3, 171);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (254, 'Laboratory centrifuges', 'Fay and Sons', 3, 148);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (255, 'Anesthesia carts', 'Schoen-Spinka', 4, 152);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (256, 'Oxygen cylinders', 'Nikolaus, Heidenreich and Pacocha', 1, 161);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (257, 'Fetal monitors', 'Torphy, Crooks and Howell', 3, 191);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (258, 'Stethoscopes', 'Vandervort-Carroll', 4, 129);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (259, 'Otoscopes', 'Tillman-Rowe', 4, 101);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (260, 'Ophthalmoscopes', 'Collins-Haley', 2, 129);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (261, 'Blood glucose meters', 'Moen Inc', 5, 164);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (262, 'Wound care supplies', 'Bahringer-Predovic', 4, 138);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (263, 'Hot packs', 'Bins, Reilly and Haley', 2, 138);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (264, 'Cold packs', 'Denesik-Johns', 1, 198);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (265, 'Electrodes', 'McKenzie, Reichert and Baumbach', 2, 166);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (266, 'Nasogastric tubes', 'Jerde-Dietrich', 3, 179);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (267, 'Urinary catheters', 'Howe LLC', 1, 131);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (268, 'Surgical masks', 'Gleichner-Sipes', 5, 147);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (269, 'Gloves', 'Ullrich Group', 3, 125);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (270, 'Gowns', 'Robel Inc', 3, 149);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (271, 'Scalpel blades', 'Bradtke-Treutel', 4, 127);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (272, 'Splints', 'Lemke, Bradtke and O''Kon', 4, 171);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (273, 'Cervical collars', 'Macejkovic LLC', 1, 138);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (274, 'Crutches', 'Armstrong-Moore', 3, 122);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (275, 'Walking aids', 'Beatty-Langosh', 4, 125);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (276, 'Glucometers', 'Paucek Group', 5, 154);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (277, 'Defibrillator pads', 'Howe and Sons', 3, 197);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (278, 'Surgical drapes', 'Kuphal Inc', 1, 140);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (279, 'Feeding tubes', 'Yost, Lindgren and O''Hara', 4, 146);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (280, 'Suture kits', 'Kihn, Zboncak and Jacobs', 2, 123);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (281, 'Nebulizer masks', 'Gusikowski and Sons', 4, 140);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (282, 'Wound dressings', 'Jakubowski, Gerhold and Bosco', 2, 192);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (283, 'Sphygmomanometers', 'Barton-Yundt', 1, 110);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (284, 'Oxygen masks', 'Stracke Group', 4, 154);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (285, 'Wheelchair ramps', 'Rath Group', 4, 150);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (286, 'Tourniquets', 'Heaney Inc', 1, 148);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (287, 'Casting materials', 'Schiller, Rutherford and Legros', 5, 150);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (288, 'Urine collection bags', 'Runolfsdottir-Yost', 3, 193);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (289, 'Hemodialysis machines', 'Wilderman-Hartmann', 1, 176);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (290, 'Cath lab equipment', 'Lowe and Sons', 1, 115);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (291, 'Microscopes', 'Corwin LLC', 2, 175);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (292, 'Blood bank refrigerators', 'Wilkinson-Bailey', 3, 182);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (293, 'Refrigerated centrifuges', 'Hintz Inc', 4, 181);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (294, 'Anesthesia vaporizers', 'Paucek-Kuvalis', 3, 101);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (295, 'Orthopedic implants', 'Hirthe, Jast and Wyman', 4, 116);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (296, 'Cryogenic storage tanks', 'Weimann-Wolff', 2, 103);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (297, 'Portable ultrasound systems', 'Rogahn, Gorczany and Runolfsson', 3, 165);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (298, 'Blood warmers', 'Davis and Sons', 4, 159);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (299, 'Dialysis machines', 'Deckow and Sons', 4, 111);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (300, 'Infusion sets', 'Krajcik and Sons', 2, 194);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (301, 'Nasal cannulas', 'Toy-Hilpert', 3, 157);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (302, 'Oxygen flow meters', 'Douglas-Wehner', 2, 127);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (303, 'Phlebotomy chairs', 'Mosciski Group', 3, 132);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (304, 'Treadmills', 'Fay and Sons', 4, 142);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (305, 'Exercise bikes', 'Borer-Streich', 2, 124);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (306, 'C-arm fluoroscopy machines', 'Kirlin LLC', 5, 128);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (307, 'Spirometers', 'Schulist, Grimes and Bergstrom', 4, 124);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (308, 'Bone densitometers', 'Wolff Inc', 2, 184);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (309, 'Pharmacy dispensing cabinets', 'Conroy, Bins and Wolf', 1, 130);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (310, 'Pharmacy compounding equipment', 'Kozey-Auer', 3, 113);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (311, 'EKG electrodes', 'Roob Group', 1, 141);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (312, 'Insulin pumps', 'Wilkinson Inc', 1, 110);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (313, 'Laparoscopic instruments', 'Kulas-Senger', 3, 168);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (314, 'Endoscopes', 'Brakus, Rutherford and McGlynn', 3, 148);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (315, 'Anesthesia masks', 'Howe-Dicki', 1, 119);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (316, 'Blood warmers', 'Koch-Predovic', 1, 139);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (317, 'Urinalysis analyzers', 'Trantow-Turcotte', 5, 132);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (318, 'Hematology analyzers', 'Haag-Emard', 2, 131);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (319, 'Chemistry analyzers', 'Schimmel, Kemmer and Kuhic', 5, 150);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (320, 'Laryngoscopes', 'Feest Group', 5, 194);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (321, 'Surgical sutures', 'Mosciski-Denesik', 4, 139);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (322, 'Intensive care unit (ICU) beds', 'Robel LLC', 2, 139);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (323, 'Dental chairs', 'Mueller Inc', 2, 146);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (324, 'Dental X-ray machines', 'Reichert-Hermiston', 4, 133);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (325, 'Dental handpieces', 'Lehner Group', 1, 184);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (326, 'Dental instruments', 'Lemke and Sons', 5, 143);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (327, 'Nebulizer compressors', 'Jerde-Renner', 5, 140);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (328, 'TENS units', 'Ratke, McClure and Carter', 4, 117);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (329, 'Pulse generators', 'Barrows-Weissnat', 4, 150);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (330, 'Glucose test strips', 'Zieme-Waters', 1, 168);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (331, 'Hemostatic agents', 'Gibson-Gottlieb', 3, 157);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (332, 'Feeding pumps', 'Greenholt, Willms and Jenkins', 4, 131);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (333, 'Oxygen concentrator filters', 'Hirthe LLC', 2, 160);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (334, 'Blood bank analyzers', 'Jacobs-Hirthe', 1, 184);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (335, 'Hospital stretchers', 'Volkman and Sons', 5, 176);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (336, 'Hospital gurneys', 'Heathcote-Bednar', 1, 157);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (337, 'Baby warmers', 'Schroeder-Anderson', 3, 171);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (338, 'Phototherapy units', 'McLaughlin-Shields', 3, 184);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (339, 'Infant incubators', 'Howe-Wiza', 3, 128);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (340, 'Fetal Dopplers', 'Johnson Group', 4, 159);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (341, 'Blood collection chairs', 'Ritchie, West and Lakin', 4, 170);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (342, 'Bone drills', 'Beier, Muller and Gerlach', 3, 174);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (343, 'Surgical staplers', 'Klein, McClure and Murazik', 4, 122);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (344, 'Laparoscopic towers', 'Pollich, Hermiston and MacGyver', 5, 154);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (345, 'Surgical smoke evacuators', 'Rolfson, Adams and Romaguera', 3, 178);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (346, 'Phacoemulsification systems', 'Borer, Wisozk and Torp', 4, 196);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (347, 'Surgical bone saws', 'Pouros Group', 4, 192);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (348, 'Neurological drills', 'Konopelski-Gislason', 5, 110);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (349, 'Surgical suction pumps', 'Schmeler and Sons', 1, 183);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (350, 'Portable X-ray units', 'Nader-Treutel', 3, 159);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (351, 'Video laryngoscopes', 'Zieme Inc', 3, 193);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (352, 'Endotracheal tubes', 'Effertz-Runolfsson', 3, 142);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (353, 'Surgical retractors', 'Gusikowski, Bradtke and Bergnaum', 2, 191);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (354, 'Bipolar forceps', 'Konopelski Inc', 1, 138);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (355, 'Laparoscopic trocars', 'Donnelly and Sons', 2, 146);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (356, 'Nasal endoscopes', 'Abbott Inc', 5, 117);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (357, 'Colposcopes', 'Schimmel, Ledner and Cassin', 2, 144);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (358, 'Cautery machines', 'Pfannerstill, Greenfelder and Yost', 1, 138);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (359, 'Surgical masks', 'Heathcote-Robel', 5, 118);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (360, 'Pulse oximeter probes', 'Heathcote, McCullough and Kreiger', 4, 137);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (361, 'EKG cables', 'Mraz-Brakus', 1, 177);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (362, 'Holter monitors', 'Baumbach-Douglas', 5, 187);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (363, 'Electroencephalogram (EEG) machines', 'Sauer, Rosenbaum and Lynch', 1, 106);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (364, 'Mobile radiography systems', 'Stehr LLC', 4, 193);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (365, 'Surgical bone drills', 'Ferry-Haag', 3, 196);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (366, 'Surgical power tools', 'Roob, Doyle and Terry', 5, 133);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (367, 'Surgical scissors', 'Daugherty, Luettgen and Rogahn', 3, 113);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (368, 'Speculums', 'Wunsch-Kutch', 5, 116);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (369, 'Sterile drapes', 'Lemke-Gleason', 1, 157);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (370, 'Surgical gloves', 'Daniel, Ankunding and Koss', 1, 140);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (371, 'Surgical forceps', 'Lehner, Conn and D''Amore', 3, 105);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (372, 'Surgical retractors', 'Brakus LLC', 1, 149);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (373, 'Biopsy needles', 'Powlowski LLC', 2, 112);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (374, 'Surgical brushes', 'Will-Durgan', 2, 116);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (375, 'Sigmoidoscopes', 'Schultz, Rice and Stanton', 3, 134);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (376, 'Percutaneous endoscopic gastrostomy (PEG) tubes', 'Batz-Kohler', 5, 115);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (377, 'Intraocular lenses', 'Fahey-Jast', 5, 129);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (378, 'Laser hair removal systems', 'VonRueden-Hackett', 1, 189);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (379, 'Cryosurgery units', 'Feeney, Hilll and Stroman', 3, 180);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (380, 'Suction catheters', 'Mertz, Reichel and Johnston', 2, 137);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (381, 'Sterile gauze pads', 'Wisoky-Schmidt', 1, 180);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (382, 'Surgical dressings', 'Leuschke Group', 3, 193);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (383, 'Ostomy bags', 'Harber, Farrell and Sporer', 1, 177);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (384, 'Surgical bone plates', 'Veum, Sawayn and McLaughlin', 1, 108);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (385, 'Surgical bone screws', 'Bradtke-Feil', 5, 145);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (386, 'Surgical bone pins', 'Upton Group', 2, 128);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (387, 'Surgical bone grafts', 'Marvin Group', 5, 136);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (388, 'Dental implants', 'Boehm, Parker and Nolan', 4, 105);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (389, 'Dental scalers', 'DuBuque Group', 2, 199);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (390, 'Dental extraction forceps', 'Okuneva-Nienow', 2, 140);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (391, 'Dental crowns', 'Gulgowski, Torp and Torphy', 1, 122);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (392, 'Dental root canal files', 'Brekke-Runolfsdottir', 4, 186);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (393, 'Dental anesthetics', 'Gerhold, Swaniawski and Buckridge', 1, 108);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (394, 'Dental curing lights', 'Fahey Inc', 3, 109);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (395, 'Dental burs', 'Fay Inc', 5, 196);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (396, 'Dental impression trays', 'McLaughlin, Schulist and West', 5, 140);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (397, 'Dental composites', 'Dickens, Schinner and Lesch', 4, 144);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (398, 'Dental orthodontic brackets', 'Schaden, Champlin and Cartwright', 5, 108);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (399, 'Dental orthodontic wires', 'O''Conner-Parker', 3, 133);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (400, 'Dental prophy angles', 'Doyle, Kunde and Kerluke', 1, 126);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (401, 'Dental air compressors', 'Emmerich, Bednar and Little', 2, 184);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (402, 'Dental suction units', 'Bayer-Schiller', 5, 119);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (403, 'Dental autoclaves', 'Heaney LLC', 4, 168);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (404, 'Dental hand instruments', 'Casper-Lebsack', 2, 118);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (405, 'Dental air abrasion systems', 'Wyman and Sons', 4, 142);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (406, 'Dental amalgamators', 'Dickens-Terry', 4, 198);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (407, 'Dental articulators', 'Schaefer-Friesen', 5, 193);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (408, 'Dental porcelain ovens', 'Emard LLC', 2, 138);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (409, 'Dental radiography units', 'Hartmann, Lowe and Turcotte', 5, 132);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (410, 'Dental 3D printers', 'Rohan and Sons', 5, 165);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (411, 'Dental intraoral cameras', 'Lind Inc', 1, 192);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (412, 'Dental ultrasonic scalers', 'McGlynn Group', 1, 116);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (413, 'Dental apex locators', 'Feest and Sons', 2, 111);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (414, 'Dental oral scanners', 'Powlowski, O''Connell and Graham', 4, 155);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (415, 'Dental shade guides', 'McCullough, Hamill and Bayer', 5, 189);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (416, 'Dental laboratory furnaces', 'Schultz and Sons', 2, 178);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (417, 'Dental lab benches', 'Heathcote, Kub and Collier', 5, 106);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (418, 'Dental lab handpieces', 'Stiedemann and Sons', 4, 111);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (419, 'Dental lab vacuum mixers', 'Aufderhar, Schroeder and Doyle', 4, 138);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (420, 'Dental lab casting machines', 'Schuster, Jacobi and Jacobs', 3, 197);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (421, 'Dental lab polishing units', 'Lowe, Baumbach and Feest', 4, 186);
insert into Geraete (geraet_id, geraet_name, hersteller, lager_id, mitarbeiter_id) values (422, 'Wheelchairs', 'Kling, Emmerich and Fahey', 1, 132);
