insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (501, 'Hydrocodone Bitartrate And Acetaminophen', 'Hydrocodone Bitartrate And Acetaminophen', 'D', 3, 193);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (502, 'Sycosis Complex', 'Zincum metallicum, Silicea, Sulphur, Thuja occidentalis,', 'E', 2, 179);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (503, 'nicotine', 'Nicotine Polacrilex', 'A', 3, 199);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (504, 'Blistex', 'Dimethicone, Oxybenzone, and Padimate O', 'E', 5, 165);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (505, 'CVS Maximum Strength Boil Relief', 'Benzocaine', 'A', 5, 145);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (506, 'Mens Mitchum Advanced Invisible', 'ALUMINUM ZIRCONIUM TETRACHLOROHYDREX GLY', 'B', 4, 147);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (507, 'Metronidazole', 'Metronidazole', 'E', 1, 125);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (508, 'CP Dr. Babor Purity Cellular Stop Blemish Fluid', 'Salicylic Acid', 'C', 4, 109);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (509, 'Atenolol', 'Atenolol', 'D', 2, 110);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (510, 'TINTED LIP CONDITIONER', 'OCTINOXATE, OCTISALATE', 'E', 1, 200);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (511, 'citroma', 'Magesium Citrate', 'A', 4, 141);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (512, 'Spinach', 'Spinach', 'E', 4, 130);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (513, 'Ibuprofen', 'Ibuprofen', 'C', 2, 178);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (514, 'LBel', 'TITANIUM DIOXIDE, OXYBENZONE, and OCTINOXATE', 'D', 5, 122);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (515, 'Plan B One-Step', 'levonorgestrel', 'E', 3, 129);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (516, 'AVAPRO', 'IRBESARTAN', 'C', 4, 114);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (517, 'TERUFLEX Blood Bag System Anticoagulant Citrate Phosphate Dextrose Adenine (CPDA-1)', 'Anticoagulant Citrate Phosphate Dextrose Adenine (CPDA-1)', 'D', 3, 178);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (518, 'Fosphenytoin', 'FOSPHENYTOIN SODIUM', 'E', 3, 179);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (519, 'Meclizine Hydrochloride', 'MECLIZINE HYDROCHLORIDE', 'D', 3, 198);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (520, 'Flawless Tinted Moisturizer Medium', 'Octinoxate, Octisalate, Avobenzone', 'C', 1, 148);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (521, 'FENTANYL TRANSDERMAL SYSTEM', 'fentanyl transdermal system', 'B', 4, 130);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (522, 'Livergen', 'Arnica Montana, Byronia Alba Root, Silybum Marianum Seed, Chelidonium Majus, Herring Sperm DNA, Pork Liver, Cervus Elaphus Horn Oil, Sus Scrofa Pancreas, and Taraxacum Officinale', 'C', 4, 159);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (523, 'HONIBE', 'MENTHOL', 'A', 2, 115);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (524, 'TRIAZOLAM', 'TRIAZOLAM', 'C', 2, 140);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (525, 'Actos', 'pioglitazone hydrochloride', 'A', 4, 174);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (526, 'Medi-First Burn', 'Lidocaine Hydrochloride', 'A', 2, 103);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (527, 'Fluocinonide', 'Fluocinonide', 'D', 1, 169);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (528, 'Levothyroxine Sodium', 'Levothyroxine Sodium', 'E', 5, 196);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (529, 'Aspirin', 'Aspirin', 'C', 4, 159);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (530, 'Losartan Potassium', 'Losartan Potassium', 'B', 1, 164);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (531, 'Erythromycin', 'erythromycin', 'A', 3, 109);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (532, 'BIOPLASMA SPORT WITH ELECTROLYTES', 'CALCIUM FLUORIDE, TRIBASIC CALCIUM PHOSPHATE, CALCIUM SULFATE ANHYDROUS, FERROSOFERRIC PHOSPHATE, POTASSIUM CHLORIDE, POTASSIUM PHOSPHATE, DIBASIC, MAGNESIUM PHOSPHATE, DIBASIC TRIHYDRATE, SODIUM CHLORIDE, SODIUM PHOSPHATE, DIBASIC, HEPTAHYDRATE, SODIUM SULFATE, and SILICON DIOXIDE', 'B', 2, 108);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (533, 'LBEL COULEUR LUXE AMPLIFIER XP', 'Octinoxate and Oxybenzone', 'A', 4, 101);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (534, 'RITUALS precious mineral foundation broad spectrum SPF 15 sunscreen SHADE 14', 'TITANIUM DIOXIDE', 'E', 2, 112);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (535, 'Annual Blue Grass', 'Annual Blue Grass', 'A', 3, 199);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (536, 'Theochem Foaming Hand Sanitizer', 'FOAMING HAND SANTIZER', 'C', 5, 149);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (537, 'COREG', 'carvedilol phosphate', 'D', 3, 107);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (538, 'Medium Deep Warm Perfecting Makeup Broad Spectrum SPF 25', 'Octinoxate, Titanium Dioxide', 'C', 5, 148);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (539, 'Tramadol Hydrochloride and Acetaminophen', 'Tramadol Hydrochloride and Acetaminophen', 'A', 3, 169);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (540, 'SALONPAS-HOT CAPSICUM', 'Capsaicin', 'C', 3, 198);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (541, 'Acyclovir', 'Acyclovir', 'A', 2, 192);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (542, 'Isopropyl Alcohol', 'Isopropyl Alcohol', 'E', 2, 163);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (543, 'Bumetanide', 'Bumetanide', 'E', 5, 194);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (544, 'Childrens Allergy Relief', 'cetirizine hydrochloride', 'D', 1, 161);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (545, 'topiramate', 'topiramate', 'D', 4, 196);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (546, 'LBEL', 'Avobenzone, Ensulizole, Octisalate, Octocrylene, and Oxybenzone', 'A', 1, 155);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (547, 'Albuterol Sulfate', 'Albuterol Sulfate', 'E', 2, 120);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (548, 'ORPHENADRINE CITRATE', 'ORPHENADRINE CITRATE', 'C', 1, 186);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (549, 'Lombardy Poplar', 'Lombardy Poplar', 'A', 1, 113);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (550, 'Enalapril Maleate', 'Enalapril Maleate', 'E', 3, 183);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (551, 'Butalbital, aspirin, and caffeine', 'Butalbital, aspirin, and caffeine', 'D', 1, 106);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (552, 'Levothyroxine Sodium', 'Levothyroxine Sodium', 'C', 2, 152);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (553, 'Testred', 'MethylTESTOSTERone', 'D', 4, 121);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (554, 'PIROXICAM', 'PIROXICAM', 'C', 1, 118);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (555, 'equaline hemorrhoidal', 'Mineral oil, Petrolatum, Phenylephrine HCl, Shark liver oil', 'E', 5, 193);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (556, 'FAMILY CARE HYDROCORTISONE', 'HYDROCORTISONE', 'B', 5, 133);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (557, 'Zolpidem Tartrate', 'zolpidem tartrate', 'C', 5, 126);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (558, 'Angelica UV Shield SPF 40', 'TITANIUM DIOXIDE', 'B', 4, 150);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (559, 'Ciprofloxacin Hydrochloride', 'Ciprofloxacin Hydrochloride', 'D', 1, 195);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (560, 'Corn Grain', 'Corn Grain', 'B', 1, 137);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (561, 'Escitalopram', 'Escitalopram', 'E', 5, 133);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (562, 'Ceftriaxone Sodium', 'Ceftriaxone Sodium', 'E', 1, 145);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (563, 'potassium phosphates', 'Potassium Phosphate, Monobasic and Potassium Phosphate, Dibasic', 'D', 1, 151);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (564, 'benzonatate', 'benzonatate', 'B', 1, 183);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (565, 'Methocarbamol', 'Methocarbamol', 'D', 1, 134);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (566, 'All Day Allergy Relief', 'Cetirizine HCl', 'C', 1, 176);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (567, 'Temazepam', 'temazepam', 'C', 4, 173);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (568, 'Aurum Onopordon', 'Aurum Onopordon', 'B', 1, 177);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (569, 'BANDAGE', 'benzalkonium chloride', 'C', 4, 128);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (570, 'PANTOPRAZOLE SODIUM', 'PANTOPRAZOLE SODIUM', 'B', 3, 186);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (571, 'EQUALINE', 'SELENIUM SULFIDE', 'B', 1, 110);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (572, 'Treatment Set TS351004', 'Treatment Set TS351004', 'D', 2, 165);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (573, 'Tuna Fish', 'Tuna Fish', 'D', 3, 187);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (574, 'ATOPALM Hemorrhoidal', 'MINERAL OIL, PETROLATUM, PHENYLEPHRINE HYDROCHLORIDE', 'E', 2, 156);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (575, 'Diltiazem Hydrochloride', 'DILTIAZEM HYDROCHLORIDE', 'B', 2, 196);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (576, 'Orapred', 'prednisolone sodium phosphate', 'B', 5, 154);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (577, 'Mucus Relief', 'Acetaminophen, guaifenesin, phenylephrine HCl', 'C', 5, 171);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (578, 'Sciatica', 'Aconitum napellus, Aesculus hippocastanum, Colchicum autumnale, Hypericum perforatum, Magnesia phosphorica, Plumbum metallicum, Rhus toxicodendron, Arnica Montana,', 'D', 2, 177);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (579, 'Gleevec', 'imatinib mesylate', 'E', 2, 152);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (580, 'PROPECIA', 'finasteride', 'E', 3, 115);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (581, 'DESLORATADINE', 'DESLORATADINE', 'A', 3, 106);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (582, 'CounterAct', 'Ibuprofen', 'A', 1, 137);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (583, 'SBS 40', 'Allantoin', 'E', 5, 145);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (584, 'PSEUDO-TIME', 'PSEUDOEPHEDRINE HCL', 'C', 4, 160);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (585, 'FLUOXETINE', 'fluoxetine hydrochloride', 'A', 4, 171);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (586, 'Benzamycin', 'erythromycin and benzoyl peroxide', 'D', 4, 164);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (587, 'Levetiracetam', 'levetiracetam', 'E', 4, 197);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (588, 'HAND SANITIZING', 'ALCOHOL', 'C', 4, 168);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (589, 'LEVOTHYROXINE SODIUM', 'LLEVOTHYROXINE SODIUM', 'B', 2, 125);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (590, 'Pioglitazone', 'pioglitazone', 'E', 1, 138);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (591, 'Furosemide', 'Furosemide', 'D', 4, 146);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (592, 'Risperidone', 'Risperidone', 'C', 4, 187);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (593, 'Triamterene and Hydrochlorothiazide', 'Triamterene and Hydrochlorothiazide', 'C', 5, 167);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (594, 'DOCTORS CHOICE', 'STANNOUS FLUORIDE', 'B', 2, 113);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (595, 'Doral', 'quazepam', 'C', 4, 186);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (596, 'AUREOBASIDIUM PULLULANS VAR PULLULANS', 'PULLULARIA PULLULANS', 'E', 1, 142);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (597, 'Irbesartan', 'Irbesartan', 'C', 3, 130);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (598, 'Aspirin', 'aspirin', 'B', 4, 185);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (599, 'Hydrocodone Bitartrate And Acetaminophen', 'Hydrocodone Bitartrate And Acetaminophen', 'D', 3, 193);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (600, 'Ibuprofen', 'Ibuprofen', 'D', 5, 162);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (601, 'Lilium Viscum', 'Lilium Viscum', 'E', 5, 195);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (602, 'Mirapex', 'pramipexole dihydrochloride', 'C', 2, 135);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (603, 'Dove', 'Aluminum Zirconium Tetrachlorohydrex GLY', 'A', 2, 167);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (604, 'Mentholatum Sports Pain Relief', 'Menthol', 'D', 2, 135);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (605, 'Hydrocortisone Maximum Strength', 'Hydrocortisone', 'C', 1, 162);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (606, 'Birch', 'Birch', 'E', 3, 173);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (607, 'Rilutek', 'riluzole', 'B', 4, 174);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (608, 'Olanzapine', 'Olanzapine', 'C', 2, 110);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (609, 'Neutrogena Ultimate Sport', 'Avobenzone, Homosalate, Octisalate, Octocrylene, and Oxybenzone', 'B', 3, 190);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (610, 'Nystatin', 'Nystatin', 'E', 1, 172);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (611, 'Lamb', 'Lamb', 'C', 5, 102);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (612, 'PSORIASIS CONTROL', 'SALICYLIC ACID', 'D', 4, 152);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (613, 'Indomethacin', 'Indomethacin', 'C', 5, 104);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (614, 'Warfarin Sodium', 'Warfarin Sodium', 'D', 3, 166);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (615, 'Morphine Sulfate', 'Morphine Sulfate', 'B', 2, 148);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (616, 'STANDARDIZED KENTUCKY BLUEGRASS POLLEN', 'Poa pratensis pollen', 'E', 5, 107);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (617, 'Aconitum Homaccord', 'ACONITUM NAPELLUS and EUCALYPTUS GLOBULUS LEAF and IPECAC', 'B', 3, 173);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (618, 'Plus Plus White Smokers Whitening', 'SODIUM MONOFLUOROPHOSPHATE', 'A', 5, 182);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (619, 'Bisacodyl', 'Bisacodyl', 'A', 5, 199);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (620, 'Bleomycin', 'BLEOMYCIN SULFATE', 'A', 1, 135);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (621, 'Equisetum Formica', 'Equisetum Formica', 'C', 3, 180);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (622, 'Metoprolol Succinate', 'Metoprolol Succinate', 'C', 2, 108);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (623, 'Nettle', 'Nettle', 'D', 3, 196);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (624, 'Lovastatin', 'Lovastatin', 'C', 1, 132);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (625, 'Peridex', 'chlorhexidine gluconate', 'B', 4, 170);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (626, 'Aspirin', 'Aspirin', 'C', 2, 175);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (627, 'Regular Strength Enteric coated aspirin', 'Aspirin', 'D', 3, 197);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (628, 'FLUORITAB CHEWABLE', 'SODIUM FLUORIDE', 'B', 4, 184);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (629, 'Neutrogena Beach Defense Water Plus Sun Barrier', 'Avobenzone, Homosalate, Octisalate, Octocrylene, and Oxybenzone', 'D', 1, 195);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (630, 'Fludeoxyglucose F18', 'Fludeoxyglucose F18', 'B', 4, 124);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (631, 'health mart adult tussin', 'Dextromethorphan Hydrobromide, Guaifenesin, Phenylephrine Hydrochloride', 'E', 3, 128);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (632, 'Kaopectate', 'Bismuth subsalicylate', 'A', 4, 154);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (633, 'Argatroban', 'Argatroban', 'B', 4, 192);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (634, 'Venlafaxine Hydrochloride', 'Venlafaxine', 'B', 1, 139);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (635, 'Cephalexin', 'Cephalexin', 'C', 5, 125);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (636, 'ESIKA Extreme Moisturizing SPF 16', 'Octinoxate and Oxybenzone', 'C', 4, 157);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (637, 'Antibacterial Wipes', 'BENZALKONIUM CHLORIDE', 'E', 4, 142);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (638, 'Dandruff', 'Pyrithione zinc', 'A', 4, 166);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (639, 'Tretinoin', 'Tretinoin', 'A', 3, 199);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (640, 'Bupivacaine Hydrochloride', 'BUPIVACAINE HYDROCHLORIDE', 'B', 5, 129);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (641, 'Azithromycin Dihydrate', 'azithromycin', 'C', 3, 104);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (642, 'topcare infants pain and fever', 'Acetaminophen', 'E', 4, 171);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (643, 'Helium Oxygen Mixture', 'Helium Oxygen Mixture', 'A', 4, 163);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (644, 'Lanacane Maximum Strength Anti Bacterial First Aid Spray', 'benzocaine and benzethonium chloride', 'B', 5, 114);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (645, 'Cyclobenzaprine Hydrochloride', 'cyclobenzaprine hydrochloride', 'B', 1, 197);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (646, 'Anti-Bacterial Hand', 'Alcohol', 'C', 4, 175);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (647, 'Extra Strength Back and Body', 'Aspirin, Caffeine', 'A', 3, 173);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (648, 'CELEBREX', 'Celecoxib', 'A', 2, 188);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (649, 'Oxygen', 'Oxygen', 'B', 3, 139);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (650, 'FazaClo', 'clozapine', 'C', 3, 158);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (651, 'TobraDex', 'tobramycin and dexamethasone', 'E', 2, 105);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (652, 'PureLife APF', 'Sodium Fluoride', 'D', 2, 198);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (653, 'Atomoxetine Hydrochloride', 'Atomoxetine Hydrochloride', 'B', 2, 111);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (654, 'Rhus toxicodendron', 'Rhus toxicodendron', 'B', 4, 187);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (655, 'Kiehls Since 1851 Broad Spectrum SPF 30 Sunscreen Powerful Wrinkle Reducing', 'Avobenzone, Homosalate, Octisalate and Octocrylene', 'E', 5, 178);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (656, 'Sugar Free Refreshing Mint Fishermans Friend Menthol Cough Suppressant', 'Menthol', 'D', 5, 182);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (657, 'Lady Speed Stick', 'Aluminum zirconium tetrachlorohydrex gly', 'E', 1, 193);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (658, 'Iceberg Lettuce', 'Iceberg Lettuce', 'B', 1, 109);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (659, 'Hot Spot', 'capsaicin', 'A', 4, 192);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (660, 'Perphenazine', 'PERPHENAZINE', 'C', 3, 126);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (661, 'Red (River) Birch', 'Red (River) Birch', 'B', 4, 102);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (662, 'Zonisamide', 'Zonisamide', 'A', 1, 114);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (663, 'FANAPT', 'Iloperidone', 'D', 3, 111);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (664, 'Clorox CareConcepts Bed Bath and Hygiene', '', 'C', 3, 126);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (665, 'up and up acetaminophen pm', 'Acetaminophen, Diphenhydramine HCl', 'D', 1, 172);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (666, 'Mango Blossom', 'Mango Blossom', 'B', 3, 116);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (667, 'Lisinopril', 'Lisinopril', 'B', 1, 167);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (668, 'EAR INFLAM HP', 'Atropa Belladonna Root 30X, Conium Maculatum Flowering Top 30X, Solanum Dulcamara Top 30X, Calcium Sulfide 30X, Potassium Dichromate 30X, Mercurius Solubilis 30X, Pulsatilla Vulgaris 30X, Silicon Dioxide 30X', 'B', 4, 193);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (669, 'Stibium 20 Special Order', 'Stibium 20 Special Order', 'E', 3, 137);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (670, 'Miconazole Nitrate', 'Miconazole Nitrate', 'E', 2, 103);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (671, 'Chlorpromazine Hydrochloride', 'Chlorpromazine Hydrochloride', 'A', 2, 118);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (672, 'Alprazolam', 'alprazolam', 'A', 3, 189);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (673, 'Naproxen Sodium', 'Naproxen Sodium', 'B', 1, 190);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (674, 'Oxygen', 'Oxygen', 'B', 4, 125);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (675, 'R-Tanna', 'Phenylephrine Tannate and Chlorpheniramine Tannate', 'C', 3, 164);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (676, 'LOreal Paris Skin Expertise Revitalift Deep-Set Wrinkle Repair Eye Cream', 'Avobenzone Octisalate Octocrylene', 'B', 2, 185);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (677, 'Diaper Rash', 'Zinc oxide', 'B', 5, 106);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (678, 'Sulindac', 'Sulindac', 'E', 3, 175);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (679, 'Good Neighbor Pharmacy allergy', 'Diphenhydramine Hydrochloride', 'C', 5, 154);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (680, 'NARS FOUNDATION', 'OCTINOXATE and TITANIUM DIOXIDE', 'C', 1, 112);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (681, 'Bupivacaine Hydrochloride and Epinephrine', 'BUPIVACAINE HYDROCHLORIDE AND EPINEPHRINE BITARTRATE', 'A', 3, 164);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (682, 'Famotidine', 'Famotidine', 'D', 3, 176);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (683, 'Sage', 'Sage', 'B', 3, 198);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (684, 'KIDS CHOICE', 'STANNOUS FLUORIDE', 'B', 3, 197);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (685, 'Lidocaine Hydrochloride', 'LIDOCAINE HYDROCHLORIDE', 'A', 3, 130);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (686, 'Sinus PE And Allergy Maximum Strength', 'Chlorpheniramine maleate, Phenylephrine HCl', 'D', 1, 113);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (687, 'Penicillium notatum', 'Penicillium notatum', 'D', 2, 129);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (688, 'Dove Men plus Care', 'Aluminum Zirconium Tetrachlorohydrex GLY', 'D', 5, 178);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (689, 'Olanzapine', 'Olanzapine', 'D', 1, 193);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (690, 'Dipyridamole', 'Dipridamole', 'E', 4, 182);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (691, 'ZOFRAN', 'ondansetron hydrochloride', 'A', 3, 118);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (692, 'CONDITION AND ENHANCE SYSTEM', 'HYDROQUINONE, OCTINOXATE AND ZINC OXIDE', 'E', 1, 174);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (693, 'Antibacterial Hand', 'Triclosan', 'D', 5, 195);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (694, 'Galentic Vitamin A D', 'Petrolatum', 'A', 1, 199);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (695, 'Neutrogena MoistureShine SPF20', 'Octinoxate, Octisalate, and Titanium Dioxide', 'A', 3, 131);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (696, 'Hemorrhoidal Hygiene pads', 'witch hazel', 'C', 1, 196);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (697, 'omeprazole', 'Omeprazole', 'A', 1, 155);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (698, 'Amlodipine Besylate and Benazepril Hydrochloride', 'Amlodipine Besylate and Benazepril Hydrochloride', 'D', 2, 139);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (699, 'Phenelzine Sulfate', 'Phenelzine Sulfate', 'A', 2, 172);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (700, 'Lithium Carbonate', 'Lithium Carbonate', 'B', 1, 188);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (701, 'HyperHEP B S/D', 'Hepatitis B Immune Globulin (Human)', 'D', 1, 118);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (702, 'Enoxaparin sodium', 'enoxaparin sodium', 'E', 3, 180);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (703, 'Celeragesic', 'Echinacea (Angustifolia), Echinacea purpurea, Bellis perennis, Calendula officinalis, Hamamelis virginiana, Aconitrum napellus, Chamomilla, Hypericum perforatum, Belladonna,', 'D', 4, 170);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (704, 'Omeprazole', 'Omeprazole', 'E', 3, 132);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (705, 'Canary Grass', 'Canary Grass', 'A', 4, 188);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (706, 'Softlips', 'dimethicone, octinoxate, octisalate, oxybenzone', 'C', 4, 129);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (707, 'FLORIL REDNESS RELIEF', 'NAPHAZOLINE HYDROCHLORIDE', 'D', 4, 185);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (708, 'Hydromorphone Hydrochloride', 'Hydromorphone Hydrochloride', 'E', 3, 111);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (709, 'Exchange Select Dark Tanning Sunscreen', 'OCTOCRYLENE', 'B', 4, 123);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (710, 'Goose Feathers', 'Goose Feathers', 'D', 3, 190);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (711, 'BERRY BABY LIP BALM VIOLET BERRY', 'OCTINOXATE, TITANIUM DIOXIDE', 'A', 4, 171);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (712, 'Doxycycline', 'Doxycycline', 'A', 5, 158);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (713, 'Hand Sanitizer', 'alcohol', 'E', 1, 150);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (714, 'Sunmark Nicotine', 'Nicotine Polacrilex', 'A', 2, 137);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (715, 'Snore Soothe', 'Histaminum hydrochloricum Laccaninum, Arsenicum alb., Belladonna Bryonia,Camphora, Cistus canadensis, Drosera, Hepar sulph.calc., Hydrastis, Ignatia, Iodium, Kali bic.,Kali iod., Nux vom., Phosphorus, Pulsatilla,Sabadilla, Silicea, Sticta, Sulphur, Teucriummarum, Verbascum, Echinacea.', 'E', 3, 112);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (716, 'Baclofen', 'Baclofen', 'E', 5, 132);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (717, 'Allersode', 'Allium cepa, Ambrosia artemisiaefolia, Euphrasia officinalis', 'E', 1, 166);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (718, 'Altoprev', 'lovastatin', 'E', 5, 173);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (719, 'Halibut', 'Halibut', 'E', 3, 103);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (720, 'Nicorelief', 'Nicotine Polacrilex', 'E', 1, 110);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (721, 'CARMEX strawberry lip balm BROAD SPECTRUM SPF 15 SUNSCREEN', 'AVOBENZONE, OCTISALATE, HOMOSALATE, OCTOCRYLENE', 'B', 3, 152);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (722, 'Sodium Chloride', 'Sodium Chloride', 'A', 3, 123);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (723, 'VoSoL HC', 'hydrocortisone and acetic acid', 'B', 2, 115);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (724, 'Exelon', 'rivastigmine tartrate', 'A', 2, 128);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (725, 'ERYTHROMYCIN', 'Erythromycin', 'E', 5, 126);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (726, 'Octreotide Acetate', 'Octreotide Acetate', 'C', 3, 116);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (727, 'Listerine Advanced with Tartar Protection Antiseptic', 'Eucalyptol, Menthol, Methyl Salicylate, and Thymol', 'C', 4, 199);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (728, 'Klor-Con', 'Potassium Chloride', 'C', 2, 109);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (729, 'Miracle Foot Repair Cream', 'Menthol', 'E', 4, 199);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (730, 'Hydrocortisone Maximum Strength with Aloe', 'Hydrocortisone', 'E', 3, 179);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (731, 'Painful Urination', 'BERBERIS VULGARIS ROOT BARK - TURPENTINE - LYCOPODIUM CLAVATUM SPORE', 'C', 1, 107);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (732, 'Allscale', 'Allscale', 'E', 2, 151);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (733, 'Pike', 'Pike', 'E', 1, 132);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (734, 'MILK OF MAGNESIA ORIGINAL', 'magnesium hydroxide', 'B', 5, 147);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (735, 'Foaming Hand Sanitizer', 'Benzalkonium Chloride', 'C', 4, 195);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (736, 'Adapalene', 'Adapalene', 'C', 4, 146);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (737, 'miconazole 7', 'Miconazole nitrate', 'B', 4, 180);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (738, 'rx act ibuprofen', 'Ibuprofen', 'E', 1, 191);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (739, 'CHANTECAILLE Ultra Sun Protection Sunscreen Broad Spectrum SPF 30', 'AVOBENZONE, OCTINOXATE, OCTISALATE, OCTOCRYLENE', 'A', 3, 164);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (740, 'Hand Sanitizer', 'Ethyl Alcohol', 'B', 3, 196);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (741, 'pain relief', 'Acetaminophen', 'D', 4, 112);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (742, 'Western Juniper', 'Western Juniper', 'C', 4, 141);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (743, 'Metronidazole', 'Metronidazole', 'A', 2, 164);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (744, 'LORTAB', 'Hydrocodone Bitartrate and Acetaminophen', 'D', 2, 116);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (745, 'Allergy Relief', 'Diphenhydramine HCl', 'E', 3, 165);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (746, 'TUMS', 'calcium carbonate', 'B', 1, 102);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (747, 'NATURAL HONEY HERB COUGH SUPPRESSANT THROAT DROPS', 'MENTHOL', 'B', 3, 191);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (748, 'Alcohol Prep Pad', 'Isopropyl Alcohol', 'E', 5, 142);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (749, 'Ginger', 'Ginger', 'C', 1, 186);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (750, 'Phenytoin', 'Phenytoin', 'B', 4, 139);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (751, 'Stool Softener', 'Docusate Sodium', 'E', 3, 153);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (752, 'LORATADINE', 'LORATADINE', 'C', 1, 168);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (753, 'QUDEXY', 'Topiramate', 'C', 1, 164);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (754, 'Nikki', 'drospirenone and ethinyl estradiol', 'C', 5, 170);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (755, 'HydrALAZINE Hydrochloride', 'HydrALAZINE Hydrochloride', 'A', 5, 175);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (756, 'oxybutynin chloride', 'oxybutynin chloride', 'E', 1, 133);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (757, 'ONDANSETRON HYDROCHLORIDE', 'ONDANSETRON HYDROCHLORIDE', 'C', 5, 183);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (758, 'Anticavity Rinse', 'Sodium Fluoride', 'D', 4, 123);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (759, 'Allopurinol', 'Allopurinol', 'D', 5, 188);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (760, 'topcare nicotine polacrilex', 'Nicotine Polacrilex', 'A', 4, 118);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (761, 'Rite Aid Original Strength Vagicaine', 'BENZOCAINE and RESORCINOL', 'D', 2, 148);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (762, 'STUDIO MOISTURE TINT', 'OCTINOXATE', 'A', 4, 165);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (763, 'Diltiazem Hydrochloride', 'Diltiazem Hydrochloride', 'A', 4, 122);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (764, 'Smart Sense Triple Antibiotic', 'bacitracin zinc, neomycin, polymyxin B', 'B', 3, 154);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (765, 'Neutrogena Rapid Clear 2 in 1 Fight and Fade', 'Salicylic Acid', 'D', 1, 176);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (766, 'LOMBARDY POPLAR POLLEN', 'populus nigra pollen', 'E', 2, 159);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (767, 'cephalexin', 'cephalexin', 'E', 4, 124);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (768, 'Carbon Dioxide', 'Carbon Dioxide', 'B', 1, 160);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (769, 'PredniSONE', 'PredniSONE', 'B', 2, 177);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (770, 'Junior Strength Pain Reliever Grape', 'Acetaminophen', 'A', 5, 182);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (771, 'Aspirin', 'Aspirin', 'B', 5, 109);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (772, 'CONSTIPATION', 'ARSENIC', 'C', 5, 200);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (773, 'SaniSuds E-2 Foam Sanitizing Hand', 'Benzalkonium Chloride', 'A', 4, 127);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (774, 'Nuvigil', 'ARMODAFINIL', 'D', 3, 146);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (775, 'good neighbor pharmacy ibuprofen', 'Ibuprofen', 'B', 3, 150);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (776, 'Colgate', 'SODIUM MONOFLUOROPHOSPHATE', 'D', 4, 128);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (777, 'Food - Plant Source, Soybean Glycine soja', 'Soybean Glycine soja', 'D', 1, 147);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (778, 'Prochieve', 'progesterone', 'D', 2, 139);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (779, 'Acetaminophen and Codeine', 'Acetaminophen and Codeine', 'C', 3, 160);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (780, 'ALLOPURINOL', 'ALLOPURINOL', 'E', 1, 187);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (781, 'Lotrel', 'amlodipine besylate and benazepril hydrochloride', 'B', 3, 173);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (782, 'elements anti aging vitamin complex', 'Avobenzone, Ensulizole, Octisalate, Octocrylene', 'E', 2, 197);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (783, 'Bryaconeel', 'ACONITUM NAPELLUS and BRYONIA ALBA ROOT and PHOSPHORUS', 'E', 5, 117);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (784, 'Folbic', 'Pyridoxine and Cyanocobalamin and Folic Acid', 'B', 3, 191);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (785, 'CASUARINA EQUISETIFOLIA POLLEN', 'Australian Pine Beefwood', 'D', 4, 118);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (786, 'Acetylcysteine', 'acetylcysteine', 'A', 3, 145);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (787, 'Clopidogrel Bisulfate', 'clopidogrel', 'C', 5, 181);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (788, 'Fentanyl Citrate', 'Fentanyl Citrate', 'D', 2, 146);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (789, 'Penicillin V Potassium', 'Penicillin V Potassium', 'B', 4, 126);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (790, 'Leucovorin Calcium', 'Leucovorin Calcium', 'A', 3, 190);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (791, 'Super Aqua Facial Foam', 'Glycerin', 'E', 1, 173);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (792, 'PERFECTION LUMIERE', 'TITANIUM DIOXIDE', 'E', 1, 200);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (793, 'expectorant', 'Guaifenesin', 'E', 4, 151);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (794, 'ALCOHOL FREE HAND SANITIZER', 'BENZALKONIUM CHLORIDE', 'B', 5, 148);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (795, 'CELLULAR RADIANCE SUNSCREEN SPF 30', 'OCTINOXATE, OCTISALATE, OXYBENZONE', 'C', 2, 130);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (796, 'DG health calcium antacid', 'Calcium carbonate', 'B', 2, 180);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (797, 'Healthy Makeup', 'TITANIUM DIOXIDE', 'E', 2, 164);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (798, 'Nevirapine', 'Nevirapine', 'C', 2, 144);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (799, 'Loratadine and Pseudoephedrine Sulfate', 'Loratadine and Pseudoephedrine Sulfate', 'E', 5, 126);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (800, 'TRAMADOL HYDROCHLORIDE', 'TRAMADOL HYDROCHLORIDE', 'A', 4, 189);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (801, 'Doxycycline', 'Doxycycline hyclate', 'D', 1, 148);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (802, 'pain and fever', 'Acetaminophen', 'E', 2, 138);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (803, 'Carvedilol', 'Carvedilol', 'E', 5, 112);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (804, 'Hydrocortisone', 'Hydrocortisone', 'A', 2, 161);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (805, 'Gentamicin Sulfate', 'Gentamicin Sulfate', 'E', 2, 198);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (806, 'Doxycycline', 'Doxycycline', 'E', 1, 197);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (807, 'Lovastatin', 'Lovastatin', 'E', 3, 145);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (808, 'flu and sore throat', 'acetaminophen,pheniramine maleate, phenylephrine hydrochloride', 'E', 3, 121);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (809, 'PROPOLIS', 'SODIUM MONOFLUOROPHOSPHATE, SODIUM FLUORIDE', 'C', 1, 156);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (810, 'Hepar sulfuris Sinus', 'Hepar sulfuris Sinus', 'E', 1, 194);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (811, 'CLONIDINE HYDROCHLORIDE', 'clonidine hydrochloride', 'A', 1, 140);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (812, 'Cymbalta', 'Duloxetine hydrochloride', 'C', 4, 109);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (813, 'Upper GI Restoration', 'Aceticum acidum, Agaricus muscarius, Aloe socotrina, Antimonium crudum, Argentum nitricum, Carbo vegetabilis, Carduus marianus, Chelidonium majus, Chenopodium anthelminticum, Cinchona officinalis, Graphites, Ipecacuanha, Lac defloratum, Mentha piperita, Nux vomica, Secale cornutum, Tanacetum vulgare, Teucrium marum, Zingiber officinale', 'C', 3, 151);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (814, 'care one cold head congestion', 'Acetaminophen, Chlorpheniramine maleate, Dextromethorphan HBr, Phenylephrine HCl', 'A', 2, 189);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (815, 'Egotistical', 'Ferrum metallicum, Gratiola officinalis, Hamamelis virginiana, Helianthus annuus, Hottonia palustris, flos, Lachesis mutus, Lilium tigrinum, Lycopodium clavatum, Moschus, Palladium metallicum, Platinum metallicum, Staphysagria, Sulphur, Rhus toxicodendron, Veratrum album, Viola odorata', 'A', 2, 200);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (816, 'Citalopram Hydrobromide', 'Citalopram Hydrobromide', 'E', 5, 163);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (817, 'Sunmark z sleep', 'Diphenhydramine HCl', 'C', 3, 151);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (818, 'METOPROLOL SUCCINATE', 'METOPROLOL SUCCINATE', 'A', 2, 115);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (819, 'care one pain relief', 'Acetaminophen', 'B', 1, 177);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (820, 'Black Walnut', 'Black Walnut', 'E', 4, 126);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (821, 'stila CC color correcting broad-spectrum SPF 20 08 TAN', 'OCTOCRYLENE, OCTISALATE, AVOBENZONE, OCTINOXATE', 'A', 3, 106);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (822, 'Hydrocortisone', 'Hydrocortisone', 'C', 1, 179);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (823, 'Skin Klear Acne Relief', 'TRIBASIC CALCIUM PHOSPHATE,FUMARIA OFFICINALIS FLOWERING TOP,ARCTIUM LAPPA ROOT,SODIUM CHLORIDE,SAPONARIA OFFICINALIS ROOT,SILICON DIOXIDE,SOLIDAGO VIRGAUREA FLOWERING TOP,SULFUR,VIOLA TRICOLOR.', 'D', 4, 110);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (824, 'HYVEE', 'EUCALYPTOL, MENTHOL, METHYL SALICYLATE, THYMOL', 'E', 4, 102);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (825, 'Heart Ache', 'Aloe socotrina, Ambra grisea, Ammonium muriaticum, Antimonium crudum, Aurum metallicum, Borago officinalis, Cichorium intybus, flos, Cimicifuga racemosa, Eriodictyon californicum, Ignatia amara, Ilex aquifolium, flos, Iodium, Natrum muriaticum, Phosphoricum acidum, Rosa damascena, Stannum metallicum, Tilia europaea', 'A', 5, 139);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (826, 'Cranberry Orange Antibacterial Foaming Hand Wash', 'Triclosan', 'E', 4, 158);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (827, 'Glyburide', 'Glyburide', 'A', 3, 191);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (828, 'FreAmine HBC', 'ISOLEUCINE, LEUCINE, LYSINE, METHIONINE, PHENYLALANINE, THREONINE, TRYPTOPHAN, VALINE, ALANINE, ARGININE, HISTIDINE, PROLINE, SERINE, GLYCINE, CYSTEINE, and SODIUM BISULFITE', 'C', 2, 184);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (829, 'ESIKA', 'OCTINOXATE and OXYBENZONE', 'A', 5, 189);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (830, 'Nighttime Cold and Flu Relief', 'Acetaminophen, Dextromethorphan HBr, Doxylamine succinate', 'B', 2, 179);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (831, 'Antiacterial Hand Sanitizer', 'Alcohol', 'C', 5, 132);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (832, 'Morphine Sulfate', 'Morphine Sulfate', 'B', 1, 191);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (833, 'OXYGEN', 'OXYGEN', 'C', 2, 190);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (834, 'Ramipril', 'Ramipril', 'C', 4, 198);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (835, 'Candy Apple Anti Bacterial Foaming Hand', 'TRICLOSAN', 'E', 1, 187);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (836, 'Citalopram', 'Citalopram', 'B', 4, 115);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (837, 'Sensipar', 'cinacalcet hydrochloride', 'B', 1, 168);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (838, 'LARIN 1.5/30', 'Norethindrone Acetate/Ethinyl Estradiol', 'B', 1, 122);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (839, 'Toffee', 'Titanium Dioxide, Octinoxate/EthylhexylMehtoxycinnamate', 'A', 3, 185);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (840, 'Ondansetron Hydrochloride', 'Ondansetron Hydrochloride', 'E', 5, 106);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (841, 'topcare fever reducer', 'Acetaminophen', 'C', 5, 168);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (842, 'Escitalopram', 'Escitalopram', 'B', 1, 140);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (843, 'NUCYNTA', 'tapentadol hydrochloride', 'A', 2, 120);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (844, 'Brush on Block Mineral Sunscreen Broad Spectrum SPF 30', 'Titanium Dioxide 15%, Zinc Oxide 12%', 'D', 2, 193);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (845, 'equaline allergy and congestion relief', 'Loratadine, Pseudoephedrine', 'C', 5, 131);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (846, 'SODIUM SULFACETAMIDE, SULFUR', 'SODIUM SULFACETAMIDE, SULFUR', 'B', 5, 141);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (847, 'Zenol Mild Hot', 'METHYL SALICYLATE', 'E', 4, 168);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (848, 'Lactated Ringers', 'Sodium chloride, potassium chloride, sodium lactate and calcium chloride', 'E', 3, 116);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (849, 'topcare headache formula', 'Acetaminophen, Aspirin, Caffeine', 'D', 5, 179);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (850, 'Nighttime Sleep Aid', 'Diphenhydramine Hydrochloride', 'A', 5, 152);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (851, 'TachoSil', 'THROMBIN HUMAN and FIBRINOGEN', 'A', 4, 130);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (852, 'EQUATE', 'BENZALKONIUM CHLORIDE', 'A', 2, 107);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (853, 'Neutrogena Spectrum plus Advanced Sunblock', 'Avobenzone, Homosalate, Octisalate, Octocrylene, and Oxybenzone', 'B', 1, 132);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (854, 'Eczema Rescue', 'Carbolicum acidum, Fagopyrum esculentum, Hydrastis canadensis, Hydrocotyle asiatica, Juglans regia, Vinca minor,', 'D', 3, 126);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (855, 'Glipizide', 'Glipizide', 'B', 4, 159);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (856, 'ECLIPSE SPF 50', 'TITANIUM DIOXIDE, ZINC OXIDE', 'A', 5, 139);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (857, 'Bumetanide', 'Bumetanide', 'A', 5, 163);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (858, 'Neutrogena Oil-Free Acne Wash', 'Salicylic Acid', 'B', 2, 141);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (859, 'West Wheat Grass', 'West Wheat Grass', 'E', 4, 113);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (860, 'VFEND', 'VORICONAZOLE', 'A', 3, 140);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (861, 'Citalopram', 'Citalopram', 'C', 4, 114);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (862, 'Melatonin Forte', 'Melatonin, Nadidum, Niacin, Pyridoxinum hydrochloricum, Zincum sulphuricum, Hypothalamus, Lithium carbonicum, Magnesia carbonica, Pineal, Pituitary,', 'D', 3, 160);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (863, 'Phenylephrine Hydrochloride', 'Phenylephrine Hydrochloride', 'C', 5, 161);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (864, 'RISPERDAL', 'risperidone', 'C', 1, 116);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (865, 'Norethindrone Acetate', 'Norethindrone', 'A', 1, 146);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (866, 'Melvita PROSUN High protection sunscreen Broad Spectrum SPF 50', 'TITANIUM DIOXIDE, ZINC OXIDE', 'D', 3, 193);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (867, 'Haloperidol', 'Haloperidol', 'B', 3, 180);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (868, 'Metoprolol Succinate', 'Metoprolol Succinate', 'D', 2, 170);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (869, 'BABYS BUTT AID', 'ZINC OXIDE', 'A', 5, 142);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (870, 'Jelly Bean Antibacterial Hand', 'BENZALKONIUM CHLORIDE', 'C', 3, 157);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (871, 'Adalat CC', 'nifedipine', 'A', 4, 166);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (872, 'healthy accents pain relief', 'Acetaminophen', 'C', 2, 168);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (873, 'Ranitidine', 'Ranitidine Hydrochloride', 'B', 2, 163);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (874, 'Diltiazem Hydrochloride', 'diltiazem hydrochloride', 'C', 4, 178);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (875, 'LBEL EFFET PARFAIT Polvos Compactos de Larga Duracion para rostro FPS 15 /Long Lasting Compact SPF 15', 'Zinc Oxide and Titanium Dioxide', 'A', 2, 163);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (876, 'Minocin Kit', 'minocycline hydrochloride', 'C', 3, 177);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (877, 'Fluconazole', 'Fluconazole', 'A', 2, 195);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (878, 'carboplatin', 'carboplatin', 'A', 3, 153);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (879, 'Triamterene and Hydrochlorothiazide', 'Triamterene and Hydrochlorothiazide', 'C', 1, 162);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (880, 'ZOLPIDEM TARTRATE', 'zolpidem tartrate', 'D', 2, 108);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (881, 'Lidocaine Hydrochloride', 'LIDOCAINE HYDROCHLORIDE ANHYDROUS', 'A', 4, 180);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (882, 'tramadol hydrochloride', 'tramadol hydrochloride', 'A', 4, 140);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (883, 'Methocarbamol', 'methocarbamol', 'B', 1, 187);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (884, 'Povidone-Iodine Prep Pad', 'Povidone-Iodine', 'A', 1, 109);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (885, 'Live Better', 'Terbinafine Hydrochloride', 'E', 5, 122);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (886, 'Oral Dent', 'Eucalyptol, Thymol, Methyl Salicylate, Menthol', 'C', 3, 154);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (887, 'Aruba Aloe Very Water Resistant Sunscreen - For Faces', 'HOMOSALATE, OCTINOXATE, PADIMATE O, OXYBENZONE', 'C', 2, 109);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (888, 'milk of magnesia', 'Magnesium hydroxide', 'B', 3, 169);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (889, 'Temazepam', 'temazepam', 'C', 4, 117);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (890, 'Anagallis Taraxacum', 'Anagallis Taraxacum', 'B', 2, 152);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (891, 'Potassium Citrate', 'Potassium Citrate', 'A', 3, 178);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (892, 'FACE IT Radiance Two Way Cake NB23', 'TITANIUM DIOXIDE, OCTINOXATE, ZINC OXIDE', 'B', 4, 172);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (893, 'Arnuity Ellipta', 'fluticasone furoate', 'B', 1, 129);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (894, 'Coppertone waterBABIES Sunscreen', 'avobenzone, homosalate, octisalate, octocrylene, and oxybenzone', 'D', 4, 164);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (895, 'McKesson Alcohol Prep Pad', 'Isopropyl Alcohol', 'E', 5, 174);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (896, 'HGH Plus IGF1 and IGF2', 'Arnica Montana, Deer Antler Velvet, Hepar Bovine, HGH, IGF, Pituitaria Glandula Bovine, Thuja Occidentalis', 'A', 3, 120);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (897, 'Argatroban', 'Argatroban', 'A', 3, 181);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (898, 'DIPHENHYDRAMINE HYDROCHLORIDE', 'DIPHENHYDRAMINE HYDROCHLORIDE', 'E', 5, 148);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (899, 'UltrasolSunscreen', 'Avobenzone, Octinoxate, Octisalate, Oxybenzone', 'A', 1, 185);
insert into Medikamente (medikament_id, medikament_name, wirkstoff, klassifizierung, lager_id, mitarbeiter_id) values (900, 'Pleo Ut S', 'mycobacterium phlei', 'C', 4, 164);
